language: erlang

os:
  - linux

otp_release:
   - 19.3
   - 20.3
   - 21.3
   - 22.3
   - 23.0

script:
  - rebar3 --version
  - erl -version
  - rebar3 as test lint
  - rebar3 dialyzer
  - rebar3 ct
